include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - bindings/**
    - web_site/**
    - tool/**
    - test/**

linter:
  rules:
    avoid_print: false
    prefer_interpolation_to_compose_strings: false
    unnecessary_brace_in_string_interps: false
    non_constant_identifier_names: false
    prefer_final_fields: false
    prefer_conditional_assignment: false
    unnecessary_this: false
    curly_braces_in_flow_control_structures: false
    prefer_is_empty: false
    annotate_overrides: false
