import 'dart:io';

/// Represents a recorded execution step in the physical query execution tree.
class FlightRecorderStep {
  final int stepIndex;
  final String nodeType;
  final String description;
  final int rowsProcessed;
  final int durationMicroseconds;
  final int memoryBytes;

  FlightRecorderStep({
    required this.stepIndex,
    required this.nodeType,
    required this.description,
    required this.rowsProcessed,
    required this.durationMicroseconds,
    required this.memoryBytes,
  });

  Map<String, dynamic> toJson() => {
    'stepIndex': stepIndex,
    'nodeType': nodeType,
    'description': description,
    'rowsProcessed': rowsProcessed,
    'durationMicroseconds': durationMicroseconds,
    'memoryBytes': memoryBytes,
  };
}

/// Structured diagnostic telemetry report generated by the FlightRecorder.
class FlightRecorderReport {
  final String sql;
  final int totalDurationMicroseconds;
  final int rowsReturned;
  final double cacheHitRatePercentage;
  final int peakMemoryBytes;
  final List<FlightRecorderStep> steps;

  FlightRecorderReport({
    required this.sql,
    required this.totalDurationMicroseconds,
    required this.rowsReturned,
    required this.cacheHitRatePercentage,
    required this.peakMemoryBytes,
    required this.steps,
  });

  String toMarkdown() {
    final buffer = StringBuffer();
    buffer.writeln('# 📊 Flight Recorder Diagnostics');
    buffer.writeln();
    buffer.writeln('- **Query**: `$sql`');
    buffer.writeln(
      '- **Total Execution Time**: `${(totalDurationMicroseconds / 1000).toStringAsFixed(2)} ms` (`$totalDurationMicroseconds µs`)',
    );
    buffer.writeln('- **Rows Returned**: `$rowsReturned`');
    buffer.writeln(
      '- **Cache Hit Rate**: `${cacheHitRatePercentage.toStringAsFixed(1)}%`',
    );
    buffer.writeln(
      '- **Peak Memory Allocation**: `${(peakMemoryBytes / 1024).toStringAsFixed(2)} KB`',
    );
    buffer.writeln();
    buffer.writeln('### Physical Execution Steps');
    buffer.writeln();
    buffer.writeln(
      '| Step | Operator Node | Details | Rows Processed | Duration |',
    );
    buffer.writeln('| :--- | :--- | :--- | :--- | :--- |');
    for (final step in steps) {
      final ms = (step.durationMicroseconds / 1000).toStringAsFixed(2);
      buffer.writeln(
        '| #${step.stepIndex} | `${step.nodeType}` | ${step.description} | `${step.rowsProcessed}` | `${ms} ms` |',
      );
    }
    return buffer.toString();
  }

  Map<String, dynamic> toJson() => {
    'sql': sql,
    'totalDurationMicroseconds': totalDurationMicroseconds,
    'rowsReturned': rowsReturned,
    'cacheHitRatePercentage': cacheHitRatePercentage,
    'peakMemoryBytes': peakMemoryBytes,
    'steps': steps.map((s) => s.toJson()).toList(),
  };
}

/// Central flight recorder telemetry hub for UltSQL query engine.
class FlightRecorder {
  static final List<FlightRecorderStep> _currentSteps = [];
  static Stopwatch? _sessionStopwatch;
  static String _currentSql = '';
  static bool _active = false;

  static void start(String sql, {bool resetSteps = true}) {
    _currentSql = sql;
    if (resetSteps || !_active) {
      _currentSteps.clear();
    }
    _sessionStopwatch = Stopwatch()..start();
    _active = true;
  }

  static bool get isActive => _active;

  static void recordStep({
    required String nodeType,
    required String description,
    required int rowsProcessed,
    required int durationMicroseconds,
    int memoryBytes = 0,
  }) {
    if (!_active) return;
    final index = _currentSteps.length + 1;
    _currentSteps.add(
      FlightRecorderStep(
        stepIndex: index,
        nodeType: nodeType,
        description: description,
        rowsProcessed: rowsProcessed,
        durationMicroseconds: durationMicroseconds,
        memoryBytes: memoryBytes,
      ),
    );
  }

  static FlightRecorderReport stop({
    required int rowsReturned,
    double cacheHitRatePercentage = 95.0,
  }) {
    _sessionStopwatch?.stop();
    final totalMicro = _sessionStopwatch?.elapsedMicroseconds ?? 0;
    _active = false;

    int currentMemory = 0;
    try {
      currentMemory = ProcessInfo.currentRss;
    } catch (_) {
      currentMemory = 0;
    }

    return FlightRecorderReport(
      sql: _currentSql,
      totalDurationMicroseconds: totalMicro,
      rowsReturned: rowsReturned,
      cacheHitRatePercentage: cacheHitRatePercentage,
      peakMemoryBytes: currentMemory,
      steps: List.unmodifiable(_currentSteps),
    );
  }
}
